# Generated by Django 4.2.6 on 2024-02-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlelike',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlelike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleDislike',
        ),
        migrations.DeleteModel(
            name='ArticleLike',
        ),
    ]
